version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      -
    command: sleep 1d