version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:

      - mysql-data-volume:/var/lib/mysql

volumes:
  mysql-data-volume:
